services:
  - type: web
    name: haflazhbot
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHONE_NUMBER
        value: "6285787834363"
